# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Deploy to Closed beta track"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy to Firebase app distribution"
  lane :deploy_firebase do
    begin
      firebase_app_distribution(
        groups: "testers",
        release_notes: "Fixing bug in features",
        apk_path: "../build/app/outputs/flutter-apk/app.apk",
        firebase_cli_path: "/usr/local/bin/firebase",
        firebase_cli_token: "1//09SeqdHO_RU-9CgYIARAAGAkSNwF-L9Irrq9z6KOiG7eiRkAfyPNX4vB_92tUUihM5uQ0wZPa5BAmMncakGteQDqCBNQCMh2VNsw",
        app: "1:72098826413:android:34f6a51e682d4c3a315e24"
      )
    end
  end

  ### Internal testing
  lane :internal do
    begin
      gradle(task: "clean")
      gradle(
        task: "bundle",
        build_type: 'Release',
        flags: "-Pextra-front-end-options=--no-sound-null-safety"
      )
      upload_to_play_store(
        track: 'internal',
        release_status: 'completed',
        aab: '../build/app/outputs/bundle/release/app-release.aab',
        version_code: flutter_version()["version_code"],
      )
    end
  end
end
